import test from "node:test";
import assert from "node:assert/strict";
import { createStore, KEYS, validateData, validateDraft, inspectBackup } from "../web/store.js";
import { buildSeed, migrateLegacy } from "../web/seed.js";

const check = (name, fn) => test(name, fn);
function fakeStorage(entries={}) { const map=new Map(Object.entries(entries)); let failure=null;return {map,setFailure(fn){failure=fn;},getItem(k){if(failure?.("get",k))throw Object.assign(new Error("storage failed"),{name:"SecurityError"});return map.get(k)??null;},setItem(k,v){if(failure?.("set",k))throw Object.assign(new Error("quota exceeded"),{name:"QuotaExceededError"});map.set(k,v);},removeItem(k){if(failure?.("remove",k))throw Error("remove failed");map.delete(k);} }; }
check("seed retains legacy IDs and validates",()=>{const data=buildSeed();assert(validateData(data).ok);assert(data.items.find(i=>i.id==="count-solo").prompt==="1girl, solo");assert(data.items.find(i=>i.id==="char-long-hair"));});
check("legacy edits/deletes/image/order/custom preserved",()=>{
 const raw={customCategories:[{id:"custom-cat",ja:"独自",emoji:"⭐"}],customItems:[{categoryId:"custom-cat",item:{id:"custom-item",ja:"表示名",en:"custom phrase"}}],
  categoryEdits:{count:{ja:"人数変更",emoji:"🔢"}},itemEdits:{"char-long-hair":{ja:"長い髪変更",en:"very long hair"}},images:{"custom-item":"data:image/jpeg;base64,QQ=="},
  deletedCategories:["action"],deletedItems:["count-two"],categoryOrder:["custom-cat","count"]};
 const migrated=migrateLegacy(raw,100);assert(validateData(migrated).ok);assert(migrated.categories[0].id==="custom-cat");assert(migrated.categories.find(c=>c.id==="count").name==="人数変更");assert(!migrated.categories.find(c=>c.id==="action"));assert(!migrated.items.find(i=>i.id==="count-two"));assert(migrated.items.find(i=>i.id==="custom-item").image==="data:image/jpeg;base64,QQ==");assert(migrated.items.find(i=>i.id==="char-long-hair").prompt==="very long hair");
});
check("bad legacy never converted to seed",()=>{for(const raw of [null,{customItems:"oops"},{categoryEdits:[]},{images:{x:7}}]){let rejected=false;try{migrateLegacy(raw);}catch{rejected=true;}assert(rejected);}});
check("broken saved data remains untouched",()=>{const s=fakeStorage({[KEYS.data]:"{broken"}), store=createStore({storage:s}); assert(!store.init().ok);assert(s.getItem(KEYS.data)==="{broken");});
check("broken legacy does not create main key",()=>{const s=fakeStorage({[KEYS.legacy]:'{"customItems":"oops"}'}), store=createStore({storage:s});assert(!store.init().ok);assert(s.getItem(KEYS.data)===null);assert(s.getItem(KEYS.legacy)==='{"customItems":"oops"}');});
check("guard SecurityError on storage acquisition",()=>{const store=createStore({getStorage(){throw Object.assign(Error("blocked"),{name:"SecurityError"});}});assert(!store.init().ok);assert(store.getSnapshot().status.phase==="error");});
check("duplicate selection keys/span bounds/timestamps rejected",()=>{const selection={key:"same",itemId:null,label:"A",prompt:"a",weight:1,span:{start:0,end:1}}; assert(!validateDraft({text:"a",selections:[selection,selection]}).ok);assert(!validateDraft({text:"",selections:[selection]}).ok);const data=buildSeed();data.items[0].createdAt=Infinity;assert(!validateData(data).ok);});
check("CRUD/category deletion moves items/favorite/usage",()=>{const s=fakeStorage(),store=createStore({storage:s});assert(store.init().ok);const c=store.saveCategory({name:"test"});assert(c.ok);const item=store.saveItem({label:"B",prompt:"b",categoryId:c.id});assert(item.ok);assert(store.toggleFavorite(item.id).ok);assert(store.recordUse(item.id).ok);assert(store.deleteCategory(c.id).ok);const r=store.getSnapshot().data.items.find(i=>i.id===item.id);assert(r.categoryId==="other"&&r.favorite&&r.usageCount===1);});
check("bulk tab-separated registration empty-line skip",()=>{const store=createStore({storage:fakeStorage()});store.init();const result=store.addItems("長い髪\tlong hair\n\nshort hair","character");assert(result.ok&&result.count===2);assert(!store.addItems("\t","character").ok);});
check("failed draft write keeps typed text and prior storage",()=>{const s=fakeStorage(),store=createStore({storage:s});store.init();s.setFailure((op,key)=>op==="set"&&key===KEYS.draft);const result=store.setDraft({text:"new typed input",selections:[]});assert(!result.ok);assert(store.getSnapshot().draft.text==="new typed input"&&!store.getSnapshot().draftPersisted);assert(s.getItem(KEYS.draft)===null);});
check("failed CRUD write keeps old dictionary",()=>{const s=fakeStorage(),store=createStore({storage:s});store.init();const before=JSON.stringify(store.getSnapshot().data);s.setFailure((op,key)=>op==="set"&&key===KEYS.data);assert(!store.saveCategory({name:"not saved"}).ok);assert(JSON.stringify(store.getSnapshot().data)===before);});
check("backup roundtrip span/name-only rename/history",()=>{const store=createStore({storage:fakeStorage()});store.init();const d={text:"(long hair:1.2), sunset",selections:[{key:"sel1",itemId:"char-long-hair",label:"髪",prompt:"long hair",weight:1.2,span:{start:0,end:15}}]};assert(store.setDraft(d).ok);const p=store.savePreset("saved");assert(p.ok);store.setDraft({text:"other",selections:[]});assert(store.savePreset("renamed",p.id).ok);assert(store.getSnapshot().data.presets[0].text===d.text);assert(store.loadPreset(p.id).ok);assert(store.recordHistory().ok);const backup=store.exportBackup();const inspected=inspectBackup(backup.text);assert(inspected.ok&&inspected.draft.text===d.text);assert(inspected.data.history[0].selections[0].span.end===15);});
check("history capped at100",()=>{const store=createStore({storage:fakeStorage()});store.init();store.setDraft({text:"a",selections:[]});for(let n=0;n<101;n++)assert(store.recordHistory().ok);assert(store.getSnapshot().data.history.length===100);});
check("recovery archive failure aborts import",()=>{const s=fakeStorage(),store=createStore({storage:s});store.init();const before=s.getItem(KEYS.data),backup=store.exportBackup().text;s.setFailure((op,key)=>op==="set"&&key===KEYS.recovery);assert(!store.importBackup(backup).ok);assert(s.getItem(KEYS.data)===before);});
check("second live key failure atomically restores originals",()=>{const s=fakeStorage(),store=createStore({storage:s});store.init();store.setDraft({text:"old",selections:[]});const before={data:s.getItem(KEYS.data),draft:s.getItem(KEYS.draft)};const backup=JSON.parse(store.exportBackup().text);backup.draft.text="new";let once=true;s.setFailure((op,key)=>{if(op==="set"&&key===KEYS.draft&&once){once=false;return true;}return false;});assert(!store.importBackup(JSON.stringify(backup)).ok);assert(s.getItem(KEYS.data)===before.data&&s.getItem(KEYS.draft)===before.draft);assert(store.getSnapshot().draft.text==="old");});
check("corrupt archive failure never deletes originals",()=>{const s=fakeStorage({[KEYS.data]:"{broken"}),store=createStore({storage:s});store.init();s.setFailure((op,key)=>op==="set"&&key===KEYS.corrupt);assert(!store.startFresh().ok);assert(s.getItem(KEYS.data)==="{broken");});
check("pending interrupted import rolled back on next init",()=>{const data=JSON.stringify(buildSeed()),draft=JSON.stringify({text:"previous",selections:[]});const s=fakeStorage({[KEYS.data]:data,[KEYS.draft]:JSON.stringify({text:"new",selections:[]}),[KEYS.recovery]:JSON.stringify({savedAt:100,data,draft,pending:true})});const store=createStore({storage:s});assert(store.init().ok);assert(store.getSnapshot().draft.text==="previous");assert(!JSON.parse(s.getItem(KEYS.recovery)).pending);});
check("stale tab dictionary write refused",()=>{const s=fakeStorage(),a=createStore({storage:s}),b=createStore({storage:s});a.init();b.init();assert(a.saveCategory({name:"first"}).ok);assert(!b.saveCategory({name:"stale"}).ok);assert(!JSON.parse(s.getItem(KEYS.data)).categories.find(c=>c.name==="stale"));});
check("oversize20MiB backup rejected",()=>{assert(!inspectBackup(" ".repeat(20*1024*1024+1)).ok);});
check("preset and history remain exact after source item deletion",()=>{const store=createStore({storage:fakeStorage()});store.init();const draft={text:"(long hair:1.2), free words",selections:[{key:"snapshot",itemId:"char-long-hair",label:"長い髪",prompt:"long hair",weight:1.2,span:{start:0,end:15}}]};assert(store.setDraft(draft).ok);const preset=store.savePreset("snapshot");assert(preset.ok);assert(store.recordHistory().ok);const historyId=store.getSnapshot().data.history[0].id;assert(store.deleteItem("char-long-hair").ok);store.setDraft({text:"changed",selections:[]});assert(store.loadPreset(preset.id).ok);assert(store.getSnapshot().draft.text===draft.text);assert(store.loadHistory(historyId).ok);assert(store.getSnapshot().draft.text===draft.text);});
check("duplicate selection keys inside backup preset rejected without write",()=>{const s=fakeStorage(),store=createStore({storage:s});store.init();const backup=JSON.parse(store.exportBackup().text),selected={key:"repeat",itemId:null,label:"A",prompt:"a",weight:1};backup.data.presets=[{id:"p",name:"P",text:"a, a",selections:[selected,selected],createdAt:100,updatedAt:100}];const before=s.getItem(KEYS.data);assert(!store.importBackup(JSON.stringify(backup)).ok);assert(s.getItem(KEYS.data)===before);});
check("small weight remains valid through backup roundtrip",()=>{const store=createStore({storage:fakeStorage()});store.init();const d={text:"(a:0.001)",selections:[{key:"tiny",itemId:null,label:"A",prompt:"a",weight:0.001,span:{start:0,end:9}}]};assert(store.setDraft(d).ok);const parsed=inspectBackup(store.exportBackup().text);assert(parsed.ok&&parsed.draft.selections[0].weight===0.001);});

check("history captures copied snapshot without erasing newer input",()=>{const store=createStore({storage:fakeStorage()});store.init();const copied={text:"copied text",selections:[]};store.setDraft({text:"newer input",selections:[]});assert(store.recordHistory(copied).ok);assert(store.getSnapshot().data.history[0].text==="copied text");assert(store.getSnapshot().draft.text==="newer input");});
